server:
  port: 8082
  ssl:
    key-store: certs/sample.p12
    key-store-password: "!QA2ws#ED"
    keyAlias: POSTBANKESB

spring:
  application:
    name: mobile-banking-channel-request-processor

# channel properties
channel:
  allowed-ips:
    - 192.168.1.100
    - 10.0.0.50
    - 127.0.0.1
  urls:
    deposit-url: "https://ip:port/deposit"
    withdraw-url: "https://ip:port/withdraw"
    balance-url: "https://ip:port/balance"