server:
  port: 8082
  servlet:
    context-path: /api/v1/
  ssl:
    key-store: certs/sample.p12
    key-store-password: "!QA2ws#ED"
    keyAlias: POSTBANKESB


spring:
  application:
    name: mobile-banking-channel-request-processor
  datasource:
    url: jdbc:postgresql://localhost:5433/finbanking_services
    username: finbanking
    password: finbanking
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      pool-name: api-db-pool
      minimum-idle: 3
  ## enable virtual threads to allow multiple concurrent requests
  threads:
    virtual:
      enabled: true
  ## spawn a non-daemon platform thread which keeps the JVM alive when using virtual threads
  ## if disabled, @scheduled method will stop after running once
  main:
    keep-alive: true

# channel properties
channel:
  credentials:
    password: "promptu$$"
    username: "channel-api"
  allowed-ips:
    - 192.168.1.100
    - 10.0.0.50
    - 127.0.0.1
    - 0:0:0:0:0:0:0:1
  urls:
    base-url: "https://ip:port"
    deposit-url: "${channel.urls.base-url}/deposit"
    transfer-url: "${channel.urls.base-url}/transfer"
    withdraw-url: "${channel.urls.base-url}/withdraw"
    balance-url: "${channel.urls.base-url}/balance"
    account-lookup-url: "${channel.urls.base-url}/account-lookup"
    mini-statement-url: "${channel.urls.base-url}/mini-statement"
    full-statement-url: "${channel.urls.base-url}/full-statement"
    mpesa-checkout-url: "https://ip:port/mpesa/checkout"
    mpesa-b2c-url: "https://ip:port/mpesa/b2c"
    mpesa-b2b-url: "https://ip:port/mpesa/b2b"